version: "2"
services:
  jupyter:
    image: nyradr/jupyter-docker:latest
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    #command: start_nb.sh jupyter lab --LabApp.token=''
    command: start_nb.sh jupyter notebook --NotebookApp.token=''
